name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, fireFox]

    env:
      CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Set up Firefox
      uses: browser-actions/setup-firefox@latest

    - name: Run tests with Maven on ${{ matrix.browser }}
      run: mvn test -Dbrowser=${{ matrix.browser }}
